export const NW_MAP_TILE_SIZE = 1024
export const NW_MAP_TILES_X = 32
export const NW_MAP_TILES_Y = 32
export const NW_MAP_LEVELS = 8
export const NW_MAP_WORLD_WIDTH = NW_MAP_TILES_X * NW_MAP_TILE_SIZE
export const NW_MAP_WORLD_HEIGHT = NW_MAP_TILES_Y * NW_MAP_TILE_SIZE

export const NW_MAPS = [
  {
    id: 'newworld_vitaeeterna',
    name: 'Vitae Eterna',
    bounds: {
      left: 4416,
      top: 10496,
      width: 9920,
      height: 10496,
    },
    minZoom: 1,
    maxZoom: 7,
  },
  {
    id: 'outpostrush',
    name: 'Outpost Rush',
    bounds: {
      left: 921,
      top: 11588,
      width: 721,
      height: 970,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
    hideObjectivesLayer: true,
  },
  {
    id: 'devworld',
    name: 'Dev World',
    bounds: {
      left: 0,
      top: 2048,
      width: 2048,
      height: 2048,
    },
    minZoom: 1,
    maxZoom: 6,
  },
  {
    id: 'nw_dungeon_windsward_00',
    name: 'dungeon_amrine_title',
    bounds: {
      left: 616,
      top: 1064,
      width: 360,
      height: 540,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_dungeon_edengrove_00',
    name: 'dungeon_edengrove00_title',
    bounds: {
      left: 336,
      top: 1616,
      width: 572,
      height: 600,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_dungeon_everfall_00',
    name: 'dungeon_everfall_title',
    bounds: {
      left: 324,
      top: 1080,
      width: 480,
      height: 540,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_dungeon_restlessshores_00',
    name: 'Dungeon Restless Shores 00',
    bounds: {
      left: 176,
      top: 600,
      width: 600,
      height: 480,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_dungeon_restlessshores_01',
    name: 'dungeon_restlessshores01_title',
    bounds: {
      left: 680,
      top: 1380,
      width: 564,
      height: 580,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_dungeon_reekwater_00',
    name: 'dungeon_reekwater_title',
    bounds: {
      left: 640,
      top: 980,
      width: 360,
      height: 440,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_dungeon_shattermtn_00',
    name: 'dungeon_shattermtn00_title',
    bounds: {
      left: 350,
      top: 1920,
      width: 1660,
      height: 1480,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_dungeon_brimstonesands_00',
    name: 'dungeon_brimstonesands00_title',
    bounds: {
      left: 700,
      top: 1480,
      width: 720,
      height: 720,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_dungeon_cutlasskeys_00',
    name: 'dungeon_cutlasskeys00_title',
    bounds: {
      left: 250,
      top: 1230,
      width: 460,
      height: 480,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_dungeon_greatcleave_01',
    name: 'dungeon_greatcleave01_title',
    bounds: {
      left: 480,
      top: 700,
      width: 500,
      height: 500,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_dungeon_firstlight_01',
    name: 'dungeon_firstlight01_title',
    bounds: {
      left: 380,
      top: 1280,
      width: 660,
      height: 700,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_trial_season_02',
    name: 'Trial_Season_01_title',
    bounds: {
      left: 700,
      top: 1230,
      width: 460,
      height: 480,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_trial_season_02_q13',
    name: 'Trial Season 2 Q13',
    bounds: {
      left: 800,
      top: 1200,
      width: 300,
      height: 480,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_ori_eg_questmotherwell',
    name: 'Quest_Motherwell_title',
    bounds: {
      left: 1200,
      top: 1100,
      width: 100,
      height: 200,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_ori_fl_questadiana',
    name: 'Quest_Adiana_title',
    bounds: {
      left: 800,
      top: 1200,
      width: 300,
      height: 480,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_ori_gc_questnihilo',
    name: 'Quest_Nihilo_title',
    bounds: {
      left: 800,
      top: 800,
      width: 150,
      height: 150,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_trial_season_04_daichidojo',
    name: 'trial_season_04_q02_title',
    bounds: {
      left: 290,
      top: 420,
      width: 30,
      height: 30,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_trial_season_04_deviceroom',
    name: 'trial_season_04_q06_title',
    bounds: {
      left: 140,
      top: 310,
      width: 200,
      height: 100,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_dungeon_greatcleave_00',
    name: 'dungeon_greatcleave00_title',
    bounds: {
      left: 800,
      top: 1000,
      width: 400,
      height: 600,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_trial_season_04',
    name: 'Trial_Season_04_title',
    bounds: {
      left: 200,
      top: 1000,
      width: 400,
      height: 1000,
    },
    minZoom: 1,
    maxZoom: 4,
    hidePOILayer: true,
  },
  {
    id: 'nw_arena01',
    name: 'Areana 1',
    bounds: {
      left: 700,
      top: 1480,
      width: 720,
      height: 720,
    },
    minZoom: 1,
    maxZoom: 1,
    hidePOILayer: true,
  },
  {
    id: 'nw_arena02',
    name: 'Areana 2',
    bounds: {
      left: 700,
      top: 1480,
      width: 720,
      height: 720,
    },
    minZoom: 1,
    maxZoom: 1,
    hidePOILayer: true,
  },
  {
    id: 'nw_raid_cutlasskeys_00',
    name: 'raid_cutlasskeys00_title',
    bounds: null,
  },
]
