FROM node:22-alpine
EXPOSE 4200
ENV NODE_ENV production

USER node
WORKDIR /home/node

COPY --chown=node:node ./dist/web ./app

CMD ["node", "app/server/server.mjs", "--host", "0.0.0.0", "--port", "4200", "--ssr"]
