// Code generated by "stringer -type=ChunkType"; DO NOT EDIT.

package cgf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChunkType_ANY-0]
	_ = x[ChunkType_Mesh-4096]
	_ = x[ChunkType_Helper-4097]
	_ = x[ChunkType_VertAnim-4098]
	_ = x[ChunkType_BoneAnim-4099]
	_ = x[ChunkType_GeomNameList-4100]
	_ = x[ChunkType_BoneNameList-4101]
	_ = x[ChunkType_MtlList-4102]
	_ = x[ChunkType_MRM-4103]
	_ = x[ChunkType_SceneProps-4104]
	_ = x[ChunkType_Light-4105]
	_ = x[ChunkType_PatchMesh-4106]
	_ = x[ChunkType_Node-4107]
	_ = x[ChunkType_Mtl-4108]
	_ = x[ChunkType_Controller-4109]
	_ = x[ChunkType_Timing-4110]
	_ = x[ChunkType_BoneMesh-4111]
	_ = x[ChunkType_BoneLightBinding-4112]
	_ = x[ChunkType_MeshMorphTarget-4113]
	_ = x[ChunkType_BoneInitialPos-4114]
	_ = x[ChunkType_SourceInfo-4115]
	_ = x[ChunkType_MtlName-4116]
	_ = x[ChunkType_ExportFlags-4117]
	_ = x[ChunkType_DataStream-4118]
	_ = x[ChunkType_MeshSubsets-4119]
	_ = x[ChunkType_MeshPhysicsData-4120]
	_ = x[ChunkType_CompiledBones-8192]
	_ = x[ChunkType_CompiledPhysicalBones-8193]
	_ = x[ChunkType_CompiledMorphTargets-8194]
	_ = x[ChunkType_CompiledPhysicalProxies-8195]
	_ = x[ChunkType_CompiledIntFaces-8196]
	_ = x[ChunkType_CompiledIntSkinVertices-8197]
	_ = x[ChunkType_CompiledExt2IntMap-8198]
	_ = x[ChunkType_BreakablePhysics-12288]
	_ = x[ChunkType_FaceMap-12289]
	_ = x[ChunkType_MotionParameters-12290]
	_ = x[ChunkType_FootPlantInfo-12291]
	_ = x[ChunkType_BonesBoxes-12292]
	_ = x[ChunkType_FoliageInfo-12293]
	_ = x[ChunkType_Timestamp-12294]
	_ = x[ChunkType_GlobalAnimationHeaderCAF-12295]
	_ = x[ChunkType_GlobalAnimationHeaderAIM-12296]
	_ = x[ChunkType_BspTreeData-12297]
}

const (
	_ChunkType_name_0 = "ChunkType_ANY"
	_ChunkType_name_1 = "ChunkType_MeshChunkType_HelperChunkType_VertAnimChunkType_BoneAnimChunkType_GeomNameListChunkType_BoneNameListChunkType_MtlListChunkType_MRMChunkType_ScenePropsChunkType_LightChunkType_PatchMeshChunkType_NodeChunkType_MtlChunkType_ControllerChunkType_TimingChunkType_BoneMeshChunkType_BoneLightBindingChunkType_MeshMorphTargetChunkType_BoneInitialPosChunkType_SourceInfoChunkType_MtlNameChunkType_ExportFlagsChunkType_DataStreamChunkType_MeshSubsetsChunkType_MeshPhysicsData"
	_ChunkType_name_2 = "ChunkType_CompiledBonesChunkType_CompiledPhysicalBonesChunkType_CompiledMorphTargetsChunkType_CompiledPhysicalProxiesChunkType_CompiledIntFacesChunkType_CompiledIntSkinVerticesChunkType_CompiledExt2IntMap"
	_ChunkType_name_3 = "ChunkType_BreakablePhysicsChunkType_FaceMapChunkType_MotionParametersChunkType_FootPlantInfoChunkType_BonesBoxesChunkType_FoliageInfoChunkType_TimestampChunkType_GlobalAnimationHeaderCAFChunkType_GlobalAnimationHeaderAIMChunkType_BspTreeData"
)

var (
	_ChunkType_index_1 = [...]uint16{0, 14, 30, 48, 66, 88, 110, 127, 140, 160, 175, 194, 208, 221, 241, 257, 275, 301, 326, 350, 370, 387, 408, 428, 449, 474}
	_ChunkType_index_2 = [...]uint8{0, 23, 54, 84, 117, 143, 176, 204}
	_ChunkType_index_3 = [...]uint8{0, 26, 43, 69, 92, 112, 133, 152, 186, 220, 241}
)

func (i ChunkType) String() string {
	switch {
	case i == 0:
		return _ChunkType_name_0
	case 4096 <= i && i <= 4120:
		i -= 4096
		return _ChunkType_name_1[_ChunkType_index_1[i]:_ChunkType_index_1[i+1]]
	case 8192 <= i && i <= 8198:
		i -= 8192
		return _ChunkType_name_2[_ChunkType_index_2[i]:_ChunkType_index_2[i+1]]
	case 12288 <= i && i <= 12297:
		i -= 12288
		return _ChunkType_name_3[_ChunkType_index_3[i]:_ChunkType_index_3[i+1]]
	default:
		return "ChunkType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
