// Code generated by "stringer -type=FileType"; DO NOT EDIT.

package cgf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FileType_Geometry-4294901760]
	_ = x[FileType_Animation-4294901761]
}

const _FileType_name = "FileType_GeometryFileType_Animation"

var _FileType_index = [...]uint8{0, 17, 35}

func (i FileType) String() string {
	i -= 4294901760
	if i >= FileType(len(_FileType_index)-1) {
		return "FileType(" + strconv.FormatInt(int64(i+4294901760), 10) + ")"
	}
	return _FileType_name[_FileType_index[i]:_FileType_index[i+1]]
}
